spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/athena_db
    username: postgres
    password: "@M10viper"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    com.example.demo.security: DEBUG

jwt:
  secret: athena_super_secure_jwt_secret_key_256_bits_long_enough
  access-token-expiry: 900000        # 15 min
  refresh-token-expiry: 604800000    # 7 days

